theme: jekyll-theme-cayman
description: THE LEGENDZ Is A Community, A Club And A Brawl Stars Team. THE LEGENDZ Was Founded On 2019 By Aaron. THE LEGENDZ Community Was Founded By Joe And Mr.Ice On 2020. "THE LEGENDZ"
title: THE LEGENDZ
